name: ${name}
version: ${describe}
description: ${description}
authors: [Barteks2x]
main: ${groupId}.${artifactId}.Generator
load: startup
softdepend: [ProtocolLib]
commands:
    173generator:
        description: 173generator commands
        usage: |
            /173generator regenbiomes - regenerate biomes in world you are in
            /173generator regenbiomes worldname - regenerate biomes in world worldname
permissions:
    b173gen.regenbiomes: /173generator regenbiomes command
